# -*- coding: utf-8 -*-
"""RSS FEED WERA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12IiMkEtdqcd3SK1ZVmanNIdaNDbBDUac
"""

# feed_generator.py

import feedparser
import re
from feedgen.feed import FeedGenerator

import requests
from bs4 import BeautifulSoup

def extract_social_image_url(article_url):
    try:
        response = requests.get(article_url)
        response.raise_for_status()  # Raises an HTTPError if the response status code is 4XX/5XX
        soup = BeautifulSoup(response.text, 'html.parser')
        meta_tag = soup.find('meta', property='og:image')
        if meta_tag and 'content' in meta_tag.attrs:
            return meta_tag.attrs['content']
    except Exception as e:
        print(f"Error fetching social image from {article_url}: {e}")
    return "default_image_url_here"  # Fallback image URL

def fetch_filtered_articles(rss_feeds, keywords):
    filtered_articles = []
    for feed_url in rss_feeds:
        feed = feedparser.parse(feed_url)
        for entry in feed.entries:
            content = entry.title
            if any(re.search(re.escape(keyword), content, re.IGNORECASE) for keyword in keywords):
                image_url = extract_social_image_url(entry.link)  # Extract social image URL
                article = {
                    'title': entry.title,
                    'link': entry.link,
                    'pubDate': entry.get('pubDate', 'No date provided'),
                    'image_url': image_url,  # Include extracted image URL
                }
                filtered_articles.append(article)
    return filtered_articles

def generate_html_feed(filtered_articles):
    html_content = """
    <html>
    <head>
        <title>NewsFeed</title>
        <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet'>
        <style>
            body {
                font-family: 'Open Sans', sans-serif;
                margin: 40px;
                display: flex;
                flex-wrap: wrap;
                gap: 20px;
            }
            .article-tile {
                position: relative;
                width: 200px;
                height: 200px;
                color: white;
            }
            .article-tile a {
                color: white;
                text-decoration: none;
            }
            .article-tile img {
                width: 100%;
                height: 100%;
                object-fit: cover;
            }
            .overlay {
                position: absolute;
                bottom: 0;
                background: rgba(0, 0, 0, 0.5); /* Black background with opacity */
                color: #f1f1f1;
                width: 100%;
                transition: .5s ease;
                opacity:0;
                font-size: 20px;
                padding: 20px;
                text-align: center;
            }
            .article-tile:hover .overlay {
                opacity: 1;
            }
        </style>
    </head>
    <body>
        <h1>Filtered Article Feed</h1>
    """

    for article in filtered_articles:
        html_content += f"""
        <div class="article-tile">
            <a href="{article['link']}">
                <img src="{article['image_url']}" alt="">
                <div class="overlay">{article['title']}</div>
            </a>
        </div>
        """
    
    html_content += "</body></html>"
    
    with open('index.html', 'w') as html_file:
        html_file.write(html_content)
        
rss_feeds = [
    'https://www.theguardian.com/uk/rss',
    'https://www.gov.uk/search/news-and-communications.atom',
    'https://www.bathecho.co.uk/feed/',
    'https://www.mnrjournal.co.uk/rss',
    'https://www.independent.co.uk/rss',
    'https://www.desmog.com/feed/',
    'https://www.businessgreen.com/feeds/rss',
    'https://www.telegraph.co.uk/rss.xml',
    'https://bylinetimes.com/feed/',
    'https://feeds.bbci.co.uk/news/UK/rss.xml',
    'https://www.economist.com/britain/rss.xml',
    'https://leftfootforward.org/feed/',
    'https://bathnewseum.com/feed/',
    'https://bathvoice.co.uk/feed/',
    'https://feeds.skynews.com/feeds/rss/uk.xml',
    'https://www.reutersagency.com/feed/?best-topics=environment&post_type=best',
    'https://www.standard.co.uk/news/politics/rss',
]

keywords = [
    'climate change', 'harassment', 'dentist', 'train', 'council', 'bus', 'transport',
    'Wera Hobhouse', 'Lib Dem', 'global warming', 'renewable energy', 'climate',
    'Department for Energy Security and Net Zero', 'Department for Food Environment and Rural affairs',
    'environment', 'community energy', 'Liberal Democrat', 'biodiversity', 'nuclear',
    'immigration', 'Rwanda', 'weather', 'wildfires', 'pre-payment meter', 'Bath',
    'Conservative', 'misogyny', 'sexual', 'NHS', 'Osteoporosis', 'cycling', 'Prime Minister',
    'trauma', 'eating disorder'
]

filtered_articles = fetch_filtered_articles(rss_feeds, keywords)
generate_html_feed(filtered_articles)
