name: Generate RSS Feed

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate HTML Feed
      run: python feed_generator.py  # This now generates index.html

    - name: Commit and push if changed
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add index.html  # Track index.html specifically
        git commit -m "Update HTML feed" -a || echo "No changes to commit"
        git push --set-upstream https://${{ secrets.RSS_SECRET }}@github.com/Stephaniegraceh/NewsFeed.git main || echo "No changes to push"
