name: Generate RSS Feed

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4  # Correctly using `uses`
    
    - name: Set up Python
      uses: actions/setup-python@v4  # Correctly using `uses`
      with:
        python-version: '3.10'  # Using a valid Python version
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate Feed
      run: python feed_generator.py  # Ensure this script generates feed.xml

    - name: Commit and push if changed
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add feed.xml  # Track feed.xml specifically
        git commit -m "Update feed" -a || echo "No changes to commit"
        git push || echo "No changes to push"
