name: Generate RSS Feed

on:
  schedule:
    - cron:  '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4  # Correctly using `uses`
    
    - name: Set up Python
      uses: actions/setup-python@v4  # Correctly using `uses`
      with:
        python-version: '3.10'  # Adjusted to a valid Python version
        
    - name: Install dependencies
      run: |  # Correctly using `run`
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Example of a correctly formatted step using `run`
    - name: Generate Feed
      run: python feed_generator.py

    # Example of a correctly formatted step using `run` for conditional commit
    - name: Commit and push if changed
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add feed.xml  # Add specific files to ensure they're tracked
        git diff --staged --quiet || git commit -m "Update feed"
        git push
