name: Generate RSS Feed

on:
  schedule:
    # Runs every 5 minutes
    - cron:  '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Generate Feed
      run: |
        python feed_generator.py
        # Ensure your script writes to feed.xml in the current directory
        
    - name: Commit and push if changed
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add feed.xml # Specifically add feed.xml to ensure it's tracked
        git diff --staged --quiet || git commit -m "Update feed"
        git push
